### PR TITLE
DigDog Features for weighted constants and weighted sequences

### PR DESCRIPTION
**Pull request by moychal**
Contains three main features that bias Randoop's sequence selection towards higher branch and line coverage:

- Implements a static weighting scheme for constants using a modified tf-idf formula.
- Implements a dynamic weighting scheme for executed sequences based on runtime, size, and number of times run.
- Implements a weighted random selection algorithm to randomly selecting an input sequence from a weighted distribution of sequences, given the presence of any of the above weighting schemes.

We have written a report on our findings on these features. Our results indicate that these are promising.

[DigDog-Improving-Randoop.pdf](https://github.com/randoop/randoop/files/852994/DigDog-Improving-Randoop.pdf)
Our evaluation script is here: [https://github.com/jkotalik/randoopEvaluation](url)

We need to discuss:

1. Are these features suitable for Randoop? Further tuning is possible, especially to the interaction between the two weighting schemes.
2. If suitable, how we would like to merge them. The changes are made to be as stand-alone as possible. But, they would be cleaner if integrated into the existing code and/or if the existing code is refactored further.
3. Failing tests. The runNaiveCollectionsTest in `RandoopSystemTest.java` consistently fails. Example trace: 

```
randoop.main.RandoopSystemTest > runNaiveCollectionsTest STANDARD_OUT
    Randoop:
    PUBLIC MEMBERS=119
    Explorer = randoop.generation.ForwardGenerator@619a5dff

    Normal method executions: 1900401
    Exceptional method executions: 161

    Average method execution time (normal termination):      0.0398
    Average method execution time (exceptional termination): 0.165

    No error-revealing tests to output

    Regression test output:
    Regression test count: 344
    Writing JUnit tests...

    Created file: /homes/iws/shintaku/490e1/project/randoop/build/working-directories/naive-collections-test/java/foo/bar/NaiveRegression0.java
    Created file: /homes/iws/shintaku/490e1/project/randoop/build/working-directories/naive-collections-test/java/foo/bar/NaiveRegression.java

    Invalid tests generated: 0

    Ignoring java2.util2.TreeSet.$jacocoInit() in coverage checks

    Ignoring java2.util2.Collections.access$000(java.lang.Object, java.lang.Object) in coverage checks
    Ignoring java2.util2.Collections.unmodifiableList(java2.util2.List) in coverage checks
    Ignoring java2.util2.Collections.$jacocoInit() in coverage checks

    Ignoring java2.util2.ArrayList.add(int, java.lang.Object) in coverage checks
    Ignoring java2.util2.ArrayList.$jacocoInit() in coverage checks

    Ignoring java2.util2.LinkedList.get(int) in coverage checks
    Ignoring java2.util2.LinkedList.access$100(java2.util2.LinkedList) in coverage checks
    Ignoring java2.util2.LinkedList.access$200(java2.util2.LinkedList, java2.util2.LinkedList.Entry) in coverage checks
    Ignoring java2.util2.LinkedList.access$300(java2.util2.LinkedList, java.lang.Object, java2.util2.LinkedList.Entry) in coverage checks
    Ignoring java2.util2.LinkedList.access$000(java2.util2.LinkedList) in coverage checks
    Ignoring java2.util2.LinkedList.addLast(java.lang.Object) in coverage checks
    Ignoring java2.util2.LinkedList.$jacocoInit() in coverage checks

randoop.main.RandoopSystemTest > runNaiveCollectionsTest FAILED
    java.lang.AssertionError: Excluded methods that are covered:
      java2.util2.TreeSet.tailSet(java.lang.Object)
        at org.junit.Assert.fail(Assert.java:88)
        at randoop.main.CoverageChecker.checkCoverage(CoverageChecker.java:131)
        at randoop.main.RandoopSystemTest.generateAndTestWithCoverage(RandoopSystemTest.java:970)
        at randoop.main.RandoopSystemTest.runNaiveCollectionsTest(RandoopSystemTest.java:290)
```

### CODE REVIEW

**Comment by bjkeller** [comment]
Wrap the code in lines failing javadoc with `{@code }. For instance
```
 * index such that cumulativeWeights.get(i) < point <= cumulativeWeights.get(i + 1), for index 0
```
should be 
```
 * index such that {@code cumulativeWeights.get(i) < point <= cumulativeWeights.get(i + 1)}, for index 0
```

**Comment by moychal** [comment]
We briefly discussed this with @mernst , and our team did not figure out why runNaiveCollectionsTest is failing.  Without any use of the flags `--weighted-sequences`, `--weighed-constants`, or `--output-sequence-info`, Randoop should have unchanged behavior.

**Comment by bjkeller** [comment]
We have a known problem with non-determism in the covered tests (issue #156), and perhaps you exacerbated it somehow.

Though, does this test always fail with `shuffle()`?  That method is troublesome for test generation.

**Comment by moychal** [comment]
I'm not sure. I'm trying to replicate it as all of the tests are now passing on my machine. I also did a fresh clone, running the command `./gradlew clean assemble check manual` and the tests passed.

Here's an example of what `runNaiveCollectionsTest` outputs

```
randoop.main.RandoopSystemTest > runNaiveCollectionsTest STANDARD_OUT
    Randoop:
    PUBLIC MEMBERS=119
    Explorer = randoop.generation.ForwardGenerator@619a5dff

    Normal method executions: 1011875
    Exceptional method executions: 103

    Average method execution time (normal termination):      0.0737
    Average method execution time (exceptional termination): 0.416

    No error-revealing tests to output

    Regression test output:
    Regression test count: 211
    Writing JUnit tests...

    Created file: /homes/iws/shintaku/490e1/project/randoop/build/working-directories/naive-collections-test/java/foo/bar/NaiveRegression0.java
    Created file: /homes/iws/shintaku/490e1/project/randoop/build/working-directories/naive-collections-test/java/foo/bar/NaiveRegression.java

    Invalid tests generated: 0

    Ignoring java2.util2.TreeSet.$jacocoInit() in coverage checks

    Ignoring java2.util2.Collections.$jacocoInit() in coverage checks
    Ignoring java2.util2.Collections.access$000(java.lang.Object, java.lang.Object) in coverage checks
    Ignoring java2.util2.Collections.unmodifiableList(java2.util2.List) in coverage checks

    Ignoring java2.util2.ArrayList.$jacocoInit() in coverage checks
    Ignoring java2.util2.ArrayList.add(int, java.lang.Object) in coverage checks

    Ignoring java2.util2.LinkedList.addLast(java.lang.Object) in coverage checks
    Ignoring java2.util2.LinkedList.$jacocoInit() in coverage checks
    Ignoring java2.util2.LinkedList.get(int) in coverage checks
    Ignoring java2.util2.LinkedList.access$100(java2.util2.LinkedList) in coverage checks
    Ignoring java2.util2.LinkedList.access$200(java2.util2.LinkedList, java2.util2.LinkedList.Entry) in coverage checks
    Ignoring java2.util2.LinkedList.access$300(java2.util2.LinkedList, java.lang.Object, java2.util2.LinkedList.Entry) in coverage checks
    Ignoring java2.util2.LinkedList.access$000(java2.util2.LinkedList) in coverage checks
```

**Comment by mernst** [comment]
Sometimes, when a Travis job fails, re-running it immediately makes it pass.  (This is mysterious, and it indicates nondeterminism in either the test suite or in Randoop itself.)

**Comment by bjkeller** [comment]
I would lump this under issue #156, and assume it is not necessarily an issue specific to this PR.

**Comment by bjkeller** [comment]
The master branch has been updated with a change that I'm hoping fixes the non-deterministic coverage issue in runNaiveCollections.

**Comment by bjkeller** [comment]
First, it is really great that your team implemented these strategies and did the experiments.  This is very helpful to the project.

As far as the questions from the PR go:

> 1. Are these features suitable for Randoop? Further tuning is possible, especially to the interaction between the two weighting schemes.

The evidence in your report is that the changes improve the coverage regardless of whether the weights could be tuned further, so it seems reasonable to incorporate them into Randoop.

> 2. If suitable, how we would like to merge them. The changes are made to be as stand-alone as possible. But, they would be cleaner if integrated into the existing code and/or if the existing code is refactored further.

I don't see any reason not to replace the unweighted strategies with the weighted ones.  Even with the limitations of the experiments due to uncompilable tests for wildcard-laden libraries, using the weighted strategies gives improved coverage over unweighted Randoop.

> 3. Failing tests. The runNaiveCollectionsTest in RandoopSystemTest.java consistently fails.

This is not unique to this PR and (hopefully) is resolved.

**Comment by moychal** [comment]
Ok, I will see if runNaiveCollectionsTest has changed its behavior with the new updates.

I will go ahead and replace the unweighted strategies with the weighted ones, and open a new PR.

**Pull request closed without merging**
