### PR TITLE
parser fixes

### PR DESCRIPTION
**Pull request by markro49**
terminate on parse error if debug-checks is set.  my limited testing showed no significant performance cost for --debug-checks.  We could use for in-house testing and default behavior would be unchanged.

correct parse error with embedded quotes (")

### CODE REVIEW

**Comment by markro49** [comment]
When we met yesterday, I thought we had decided to have different behavior for our internal testing vs. release.  No problem to change to always throw if that is what you prefer.

**Comment by mernst** [comment]
I misunderstood and thought this was code that would only run during testing.  If it's cheap, I would have it on all the time.  Thanks!

**Comment by markro49** [comment]
do not count timeout exceeded as a compile failure was minor nit I fixed - it has nothing to due with parse errors.

**Comment by mernst** [comment]
Thanks!

**Pull request merged**
