### PR TITLE
Fix typo in manual

### PR DESCRIPTION
**Pull request by jckling**
Change `--methodList` to `--methodlist`.

### CODE REVIEW

**Comment by mernst** [comment]
Thanks very much for noticing this typo, and for submitting a patch.  We appreciate it!

**Comment by mernst** [comment]
@jckling Can you please tell me your full name so that [the manual](https://randoop.github.io/randoop/manual/index.html#credits) can acknowledge you?

Thanks.

**Comment by jckling** [comment]
Of course, my full name is Shuqi Lin, thank you.

**Comment by mernst** [comment]
@jckling I have [added](https://github.com/randoop/randoop/commit/50e9e19e69db36965e14212ba4b21dde475f3d0f) you to the credits.

**Pull request merged**
